
name: Build binaries

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CGO_ENABLED: 0
      BINARY_NAME: pdf-md-mcp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Using latest stable Go to avoid failures if go.mod specifies a not-yet-available version
          go-version: '1.23.x'
          check-latest: true
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build cross-platform binaries
        run: make build-all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-${{ github.ref_name }}-${{ github.sha }}
          path: |
            bin/*
          if-no-files-found: error
          retention-days: 7

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.BINARY_NAME }} ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            bin/*
