name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Go Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Verify modules are tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum || (echo "Please run 'go mod tidy' locally and commit changes" && exit 1)

      - name: Run tests
        run: go test -v ./...
